#!/bin/bash
html_files=$(find . -maxdepth 1 -type f -name "*.html")  # Get list of HTML files in current directory
for file in $html_files; do
    parent_dir="../$(basename "$file")"  # Get the corresponding file path in the parent directory
    if [ ! -e "$parent_dir" ] || [ "$file" -nt "$parent_dir" ]; then
        cp "$file" "../"
    fi
done
