#!/bin/bash
html_files=$(find . -maxdepth 1 -type f -name "*.html")
for file in $html_files; do
    parent_dir="../$(basename "$file")
    if [ ! -e "$parent_dir" ] || [ "$file" -nt "$parent_dir" ]; then
        cp "$file" "../"
    fi
done
